### ISSUE TITLE
Lambdaのタイムアウトの設定を追加

### ISSUE THREAD

**Issue by tamo-tmry** [tamo-tmry/linebot-openai#7]
> Task timed out after 6.01 seconds
serverless.ymlにタイムアウトの設定を追加する

**Comment by tamo-tmry** [comment]
```
	
functions:
  hello:
    handler: handler.hello # required, handler set in AWS Lambda
    name: ${sls:stage}-lambdaName # optional, Deployed Lambda name
    description: Description of what the lambda function does # optional, Description to publish to AWS
    runtime: python3.9 # optional overwrite, default is provider runtime
    runtimeManagement:
      mode: manual # syntax required for manual, mode property also supports 'auto' or 'onFunctionUpdate' (see provider.runtimeManagement)
      arn: <aws runtime arn> # required when mode is manual
    memorySize: 512 # optional, in MB, default is 1024
    timeout: 10 # optional, in seconds, default is 6
    provisionedConcurrency: 3 # optional, Count of provisioned lambda instances
    reservedConcurrency: 5 # optional, reserved concurrency limit for this function. By default, AWS uses account concurrency limit
    tracing: PassThrough
```
https://www.serverless.com/framework/docs/providers/aws/guide/functions

timeoutで設定できるっぽい
